### ISSUE TITLE
Can't add tag anymore

### ISSUE THREAD

**Issue by Arthur-Milchior** [ankitects/anki#1697] opened 2022-02-27 16:17 UTC
Running on 92bf23df995f99b7f52f8f9a33f0b73c49648962, add-ons disabled.
When I open the browser/add note, the button on the bottom left to add tags don't do anything. I don't even get an error message in the console

**Comment by hgiesel** [comment] 2022-02-27 16:43
Duplicate of #1670

**Comment by Arthur-Milchior** [comment] 2022-02-27 17:11
sorry. I did look for open bug but the title was not clear. i never used this shortcut.

**Comment by dae** [comment] 2022-02-28 01:39
Thanks Arthur, I've added mentioned of the button to #1670

**Closed by dae** 2022-02-28 01:39 UTC
