### ISSUE TITLE
Apple Silicon support

### ISSUE THREAD

**Issue by Altitude-Dashboard** [ankitects/anki#1299] opened 2021-07-17 21:25 UTC
uname -a
Darwin Codruts-MBP.localdomain 20.5.0 Darwin Kernel Version 20.5.0: Sat May  8 05:10:31 PDT 2021; root:xnu-7195.121.3~9/RELEASE_ARM64_T8101 arm64
/usr/local/bin/python --version
Python 3.8.10
file /usr/local/bin/python
/usr/local/bin/python: Mach-O universal binary with 2 architectures: [x86_64:Mach-O 64-bit executable x86_64] [arm64:Mach-O 64-bit executable arm64]
/usr/local/bin/python (for architecture x86_64):	Mach-O 64-bit executable x86_64
/usr/local/bin/python (for architecture arm64):	Mach-O 64-bit executable arm64

brew install rsync bazelisk
cd anki
./scripts/runopt
2021/07/18 00:25:11 Downloading https://releases.bazel.build/4.0.0/release/bazel-4.0.0-darwin-arm64...
2021/07/18 00:25:11 could not download Bazel: HTTP GET https://releases.bazel.build/4.0.0/release/bazel-4.0.0-darwin-arm64 failed with error 404

**Comment by pedromassango** [comment] 2021-07-17 23:21
This seems to be an download issue. I just downloaded the latest version from the website and is working fine on my M1

**Comment by dae** [comment] 2021-07-17 23:42
Dupe of #1240

**Closed by dae** 2021-07-17 23:42 UTC

**Comment by Altitude-Dashboard** [comment] 2021-07-18 03:52
There is no bazel-4.0.0-darwin-arm64 available at:
https://releases.bazel.build/4.0.0/release/
It should use bazelisk, right?
