### ISSUE TITLE
Python runtime assertions are no longer evaluated on 2.1.50+

### ISSUE THREAD

**Issue by glutanimate** [ankitects/anki#2131] opened 2022-10-13 18:18 UTC
(thanks to @roxgib for first noticing this over on Discord)

It looks like `assert` statements in add-ons (and I assume `aqt` and `anki`) are no longer evaluated in compiled release builds of Anki 2.1.50 and up. I wasn't able to find any documentation on the change, so I was wondering if that was an intended change (e.g. as a result of running Python with the `optimize` flag), or unintentional.

AFAIK, using `assert`s for runtime checks outside of development is discouraged in Python, but quite a few add-ons probably use it in that capacity (I'm guilty of that myself, though I've tried avoiding it in more recent code).

It looks like the change hasn't really lead to any obvious add-on breakages (or ones I know of at least), but I could still see this being a pitfall for add-on devs, especially if they develop against PyPI versions of Anki.

**Comment by roxgib** [comment] 2022-10-13 21:47
Thanks @glutanimate - I noticed it because I was using assert statements to create tests for my add-on that run inside of Anki. Of course I can still do this by running Anki from the command line, but I spent quite a while wondering why my tests were all passing before realising the assert statements were being skipped when previously they were checked. If this is the intended behaviour I'll open a PR to mention it in the add-on docs so other add-on devs don't get caught out?

If possible, could assert statements still be checked when Anki is launched with DEBUG=1?

**Comment by dae** [comment] 2022-10-14 00:19
The bundling changes in 2.1.50 mean the package build is now run with -OO: https://stackoverflow.com/questions/2055557/what-is-the-use-of-the-o-flag-for-running-python. If you want the checks to be run in release builds, you could create your own debug_assert() that runs unconditionally. In the Anki codebase, almost all the asserts are only used for type narrowing in mypy, and do not provide much value in a release build.

**Comment by roxgib** [comment] 2022-10-14 07:38
I don't think we're suggesting to reverse the change, just to document it

**Comment by glutanimate** [comment] 2022-10-14 09:36
Thanks for clarifying @dae. I was mostly wondering if this was an intentional change, given that the behavior was different on -2.1.49. I don't feel particularly strongly about whether or not runtime builds of Anki should evaluate asserts, if changing that is even a possibility with the new bundling method, but I could definitely see add-on devs being confused by this behavior.

Even on the [Python board](https://discuss.python.org/t/stop-ignoring-asserts-when-running-in-optimized-mode/13132), people seem to have different stances on the utility of `-O` and best practices for production, and so I could definitely see developers coming into the ecosystem with one expectation of how asserts work and be surprised to find it's the other way in practice (in either direction). Similarly, developers still targeting both 2.1.49 and 2.1.54+ could trip over this every now and then.

So with that in mind, I would definitely vote for jotting this down somewhere in the add-on docs (thanks for the PR on that @roxgib!).

**Comment by dae** [comment] 2022-10-15 01:01
Thanks Sam! Closing via https://github.com/ankitects/addon-docs/pull/17

**Closed by dae** 2022-10-15 01:01 UTC
