### ISSUE TITLE
Sync does not become blue during review until going back to deck picker

### ISSUE THREAD

**Issue by Arthur-Milchior** [ankitects/anki#2178] opened 2022-11-03 04:53 UTC
Running on dba4925aba6f3ecbb6980651a82e64b1ffe62eb7 without add-on.

How to reproduce:
* sync
* check that the "Sync" buttons is the same color as other button (white or black depending of dark or light mode)
* select a deck to review
* review a few cards

Expected result:
* "Sync" becomes blue

Actual result:
* Sync remains of the same color than other button text. I.e. black or white depending on dark or night mode.

One need to go back to deck picker to finally see the color change. This bug is related to #2173 but, I believe, different from it

**Comment by dae** [comment] 2022-11-03 04:57
Have you enabled the v3 scheduler?

**Comment by Arthur-Milchior** [comment] 2022-11-03 05:59
No. And indeed it solves the issue

**Comment by dae** [comment] 2022-11-04 00:00
Any operation that uses the new undo infrastructure should update the status immediately, so the delayed updates should be limited to legacy code paths/add-ons.

**Comment by dae** [comment] 2022-12-03 10:20
Closing this, as the issue is limited to legacy codepaths.

**Comment by dae** [comment] 2023-12-01 03:20
Silly me forgot to actually close it. :-)

**Closed by dae** 2023-12-01 03:20 UTC
